/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planner/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Planner */
        post: operations["run_planner_api_planner_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planner/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Planner Status */
        get: operations["planner_status_api_planner_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planner/prepare-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Next Lesson
         * @description Prepare tomorrow's lesson. Called by Orchestrator (hot) or cron (cold).
         */
        post: operations["prepare_next_lesson_api_planner_prepare_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboarding Message */
        post: operations["onboarding_message_api_onboarding_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Onboarding Status */
        get: operations["onboarding_status_api_onboarding_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Preferences */
        post: operations["save_preferences_api_onboarding_preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today Lesson */
        get: operations["get_today_lesson_api_lesson_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lesson Action */
        post: operations["lesson_action_api_lesson_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Lesson
         * @description Initialize or resume today's LangGraph session.
         */
        post: operations["start_lesson_api_lesson_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_profile_patch"];
        trace?: never;
    };
    "/api/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vocab */
        get: operations["get_vocab_api_vocab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/onboarding/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** General Onboarding Start */
        post: operations["general_onboarding_start_api_learn_onboarding_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/onboarding/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** General Onboarding Message */
        post: operations["general_onboarding_message_api_learn_onboarding_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/onboarding/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** General Onboarding Confirm */
        post: operations["general_onboarding_confirm_api_learn_onboarding_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get General Project */
        get: operations["get_general_project_api_learn_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/projects/{project_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get General Dashboard */
        get: operations["get_general_dashboard_api_learn_projects__project_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/lesson/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** General Lesson Start */
        post: operations["general_lesson_start_api_learn_lesson_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learn/lesson/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** General Lesson Action */
        post: operations["general_lesson_action_api_learn_lesson_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChapterItem */
        ChapterItem: {
            /** Title */
            title: string;
            /** Lessons */
            lessons: components["schemas"]["LessonStatusItem"][];
        };
        /** DimensionState */
        DimensionState: {
            /** Mastery */
            mastery: number;
            /**
             * Sessions
             * @default 0
             */
            sessions: number;
            /** Last Reviewed */
            last_reviewed: string;
            /**
             * Trend
             * @default stable
             * @enum {string}
             */
            trend: "improving" | "stable" | "worsening";
        };
        /** GeneralLessonActionRequest */
        GeneralLessonActionRequest: {
            /** Project Id */
            project_id: number;
            /** Lesson Id */
            lesson_id: number;
            /** Type */
            type: string;
            /** Answer */
            answer?: string | null;
            /** Answers */
            answers?: string[] | null;
            /** Question */
            question?: string | null;
        };
        /** GeneralLessonStartRequest */
        GeneralLessonStartRequest: {
            /** Project Id */
            project_id: number;
            /** Lesson Id */
            lesson_id: number;
        };
        /** GeneralOnboardingConfirmRequest */
        GeneralOnboardingConfirmRequest: {
            /** Project Id */
            project_id: number;
            goal_profile: components["schemas"]["UserGoalProfile"];
            learning_map: components["schemas"]["LearningMap-Input"];
        };
        /** GeneralOnboardingMessageRequest */
        GeneralOnboardingMessageRequest: {
            /** Project Id */
            project_id: number;
            /** Message */
            message: string;
        };
        /** GeneralOnboardingStartRequest */
        GeneralOnboardingStartRequest: {
            /** Topic */
            topic: string;
            /**
             * Tier
             * @default free
             */
            tier: string;
        };
        /** GeneralOnboardingStartResponse */
        GeneralOnboardingStartResponse: {
            /** Project Id */
            project_id: number;
        };
        /** GeneralProject */
        GeneralProject: {
            /** Id */
            id: number;
            /** User Topic */
            user_topic: string;
            /**
             * Status
             * @enum {string}
             */
            status: "onboarding" | "researching" | "extracting" | "active" | "complete" | "error";
            goal_profile?: components["schemas"]["UserGoalProfile"] | null;
            learning_map?: components["schemas"]["LearningMap-Output"] | null;
            /** Notebook Id */
            notebook_id?: string | null;
            /**
             * Tier
             * @default free
             * @enum {string}
             */
            tier: "free" | "paid";
            /**
             * Budget Used
             * @default 0
             */
            budget_used: number;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LearningChapter */
        LearningChapter: {
            /** Title */
            title: string;
            /** Lessons */
            lessons: components["schemas"]["LearningLesson"][];
        };
        /** LearningLesson */
        LearningLesson: {
            /** Title */
            title: string;
            /**
             * Objectives
             * @default []
             */
            objectives: string[];
        };
        /** LearningMap */
        "LearningMap-Input": {
            /** Topic */
            topic: string;
            /** Total Weeks */
            total_weeks: number;
            /** Chapters */
            chapters: components["schemas"]["LearningChapter"][];
        };
        /** LearningMap */
        "LearningMap-Output": {
            /** Topic */
            topic: string;
            /** Total Weeks */
            total_weeks: number;
            /** Chapters */
            chapters: components["schemas"]["LearningChapter"][];
        };
        /** LessonActionRequest */
        LessonActionRequest: {
            /** Type */
            type: string;
            /** Word */
            word?: string | null;
            /** Context */
            context?: string | null;
            /** Sentence */
            sentence?: string | null;
            /** Text */
            text?: string | null;
            /** Answer */
            answer?: string | null;
            /** Response Seconds */
            response_seconds?: number | null;
        };
        /** LessonStatusItem */
        LessonStatusItem: {
            /** Id */
            id: number;
            /** Chapter */
            chapter: number;
            /** Lesson */
            lesson: number;
            /** Title */
            title: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "ready";
        };
        /** OnboardingMessageRequest */
        OnboardingMessageRequest: {
            /** Message */
            message: string;
            /**
             * Thread Id
             * @default onboarding
             */
            thread_id: string;
        };
        /** PlannerStatusResponse */
        PlannerStatusResponse: {
            /** Ready */
            ready: boolean;
            /** Ready For Tomorrow */
            ready_for_tomorrow: boolean;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Status Tomorrow */
            status_tomorrow: string;
            /** Error Tomorrow */
            error_tomorrow?: string | null;
        };
        /** ProjectDashboardResponse */
        ProjectDashboardResponse: {
            /** Id */
            id: number;
            /** User Topic */
            user_topic: string;
            /** Goal Outcome */
            goal_outcome: string;
            /** Goal Progress */
            goal_progress: number;
            /** Dimensions */
            dimensions: {
                [key: string]: components["schemas"]["DimensionState"];
            };
            /** Chapters */
            chapters: components["schemas"]["ChapterItem"][];
            /**
             * Tier
             * @default free
             * @enum {string}
             */
            tier: "free" | "paid";
            /** Budget Used */
            budget_used: number;
        };
        /** ReadyStatusResponse */
        ReadyStatusResponse: {
            /** Ready */
            ready: boolean;
        };
        /** SavePreferencesRequest */
        SavePreferencesRequest: {
            /**
             * Bandwidth Minutes
             * @default 25
             */
            bandwidth_minutes: number;
            /**
             * Writing Mode
             * @default professional
             * @enum {string}
             */
            writing_mode: "professional" | "ielts_task1" | "ielts_task2";
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Interests Update */
            interests_update: string;
        };
        /** UserGoalProfile */
        UserGoalProfile: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "english" | "skill";
            /** Topic */
            topic: string;
            /** Motivation */
            motivation: string;
            /** Goal Outcome */
            goal_outcome: string;
            /** Context */
            context: string;
            /** Current Level */
            current_level: string;
            /** Time Per Week */
            time_per_week: number;
            /** Duration Weeks */
            duration_weeks: number;
            /**
             * Constraints
             * @default []
             */
            constraints: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_planner_api_planner_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    planner_status_api_planner_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerStatusResponse"];
                };
            };
        };
    };
    prepare_next_lesson_api_planner_prepare_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    onboarding_message_api_onboarding_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboarding_status_api_onboarding_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatusResponse"];
                };
            };
        };
    };
    save_preferences_api_onboarding_preferences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePreferencesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_lesson_api_lesson_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    lesson_action_api_lesson_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_lesson_api_lesson_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_profile_api_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vocab_api_vocab_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    general_onboarding_start_api_learn_onboarding_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralOnboardingStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneralOnboardingStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    general_onboarding_message_api_learn_onboarding_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralOnboardingMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    general_onboarding_confirm_api_learn_onboarding_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralOnboardingConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_project_api_learn_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneralProject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_dashboard_api_learn_projects__project_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    general_lesson_start_api_learn_lesson_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralLessonStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    general_lesson_action_api_learn_lesson_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralLessonActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
